Algoritmo "ATIVIDADE 10"
// Disciplina   : Algoritmo
// Professor   : Gilberto
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/10/2023
Var
   a,
   b ,c: inteiro


Inicio
   para a de 1 ate 10 passo 2 faca
      para b de  1 ate 3 passo 1 faca
         se (b > 1) entao
            c <- c + b
         fimse
      fimpara
   fimpara
   escreval ("O valor de c é : " , c)
   


Fimalgoritmo