Algoritmo "atividades"
// Disciplina   : Algoritmo
// Professor   : Gilberto
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/09/2023
Var
   contador, x: inteiro


Inicio
   para x de 1000 ate 2000 passo 1 faca
      se (x mod 11 = 5) entao
      escreva (x)
         contador <- contador +1
      fimse
   fimpara
   escreva
   escreva (contador)
Fimalgoritmo