Algoritmo "teste para"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/02/2024
Var
   i,soma:inteiro


Inicio
      para i de 1 ate 5 passo 1 faca
           escreval ("Esse é o valor de i:", i)
           soma <- soma + i

      fimpara
      escreval ("soma:", soma)

Fimalgoritmo